### ISSUE TITLE
Create exhaustive example manifest for GVK: apigatewayv2.aws.upbound.io/v1beta1/API

### ISSUE THREAD

**Issue by jeanduplessis** [jeanduplessis/provider-upjet-aws#1]
### What problem are you facing?

The current example for apigatewayv2.aws.upbound.io/v1beta1/API only covers the required resources.

For example: https://github.com/jeanduplessis/provider-upjet-aws/blob/main/examples/apigatewayv2/v1beta1/api.yaml
```
apiVersion: apigatewayv2.aws.upbound.io/v1beta1
kind: API
metadata:
  annotations:
    meta.upbound.io/example-id: apigatewayv2/v1beta1/api
  labels:
    upjet.upbound.io/test-group: apigatewayv2-domainname
  name: domainname-api
spec:
  forProvider:
    region: us-west-1
    name: test-http-api
    protocolType: HTTP
```

We should create an exhaustive example that contains all the configuration parameters.

### What could help solve your problem?

1. Create a new exhaustive example (call it api-exhaustive.yaml) in the example directory for the GVK (https://github.com/jeanduplessis/provider-upjet-aws/blob/main/examples/apigatewayv2/v1beta1/).
2. Include all the resource configuration options from the CRD (https://github.com/jeanduplessis/provider-upjet-aws/blob/main/package/crds/apigatewayv2.aws.upbound.io_apis.yaml) in the example manifest.
3. Open a PR to add this new file to the repository.
4. Trigger an Uptest run for the new example file by adding a comment to the PR with: `/test-examples="examples/apigatewayv2/v1beta1/api-exhaustive.yml"`
